### ISSUE TITLE
Create A4 version of special pages

### ISSUE THREAD

**Issue by kulla** [serlo/serlo-export#134]
@elbotho can you upload A4 versions of the special pages:

* mfnf_epilogue.pdf
* mfnf_fundraising.pdf
* mfnf_participation.pdf
* mfnf_prelude.pdf

with the following names:

* mfnf_epilogue_a4.pdf
* mfnf_fundraising_a4.pdf
* mfnf_participation_a4.pdf
* mfnf_prelude_a4.pdf

into https://github.com/Lodifice/mfnf-pdf-export/tree/master/include Thanks :-)

(Ping @vroland )

**Comment by elbotho** [comment]
Will also check font sizes for A4 and page think about symmetrical margins.

**Comment by elbotho** [comment]
Current idea: Export A5 Pages that can be displayed and printed side by side (resulting in a A4 in landscape mode)

**Comment by kulla** [comment]
@elbotho A4 is enough for this since afterwards one can print this with 2 pages next to each other.

**Comment by elbotho** [comment]
@kulla true, but I'd still prefer A5 because it would require less scaling / changes I think and would make it a little bit more likely that people actually print it side by side.
Do you see downsides?

**Comment by kulla** [comment]
@elbotho, than do a A5 version first ( #140 ), so that we can create a A5 and A4 version (with scaling of A5 input). When you have time, you can create a A4 but it has low priority for now...
